version: '3'

services:
  master:
    image: husarion/foxglove-bridge:noetic-nightly
    command: roslaunch foxglove_bridge foxglove_bridge.launch port:=9090
    ports:
      - 11311:11311
      - 9090:9090
  
  detection:
    build: .
    environment:
      - "ROS_MASTER_URI=http://master:11311"
    command: python main.py detection configs/centerpoint_v2.py checkpoints/centerpoint_v2.pth -s -t points_for_save
    depends_on:
      - master
    volumes:
      - detection:/app/save
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: 1

volumes:
  detection:
    driver: local